import { PLUGIN_ID } from '../pluginId';

// This function was originally called `getTranslation(id:)` (generated by `npx @strapi/sdk-plugin init`),
// but has been renamed to `prefixKey(key:)` because it doesn't return a translation.
const prefixKey = (key: string) => `${PLUGIN_ID}.${key}`;

export { prefixKey };
